name: The Mad Researcher
favicon: null
layout_spectrum: 0.75125
typography_spectrum: 0.43132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b75bb'
    - '#f5f5f5'
    - '#000000'
    - '#88b5d8'
    - '#0000ff'
  brandStrength: 0.1875
  lightness: 0.14535464299842715
  saturation: 0.840911524835974
  rhythmicContrast: 0.7442142518702894
purpose: []
